name: CI
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.*'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.*'

jobs:
  basic:
    strategy:
      matrix:
        module:
          - name: 'go-sql-driver'
            language: 'golang'
            with_oceanbase_container: true
          - name: 'mysql-connector-java'
            language: 'java'
            with_oceanbase_container: true
          - name: 'oceanbase-client'
            language: 'java'
            with_oceanbase_container: true
          - name: 'testcontainers-java'
            language: 'java'
            with_oceanbase_container: false
          - name: 'pymysql'
            language: 'python'
            with_oceanbase_container: true
          - name: 'mysql-connector-python'
            language: 'python'
            with_oceanbase_container: true
          - name: 'mybatis-plus'
            language: 'java'
            with_oceanbase_container: false
    uses: ./.github/workflows/basic-ci.yml
    with:
      module: ${{ matrix.module.name }}
      language: ${{ matrix.module.language }}
      with_oceanbase_container: ${{ matrix.module.with_oceanbase_container }}

  application-sveltekit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
          cache-dependency-path: applications/sveltekit
      - name: Build and run sample
        run: |
          cd applications/sveltekit
          npm i --legacy-peer-deps
          npm run dev
          page="$(curl -s 'http://localhost:3000')"
          echo "$page"
